ganachecli:
  domain: private.testnet.infernos.io
  path: testnet1
  whitelistIP: "true"
  whitelistIPlist: "173.48.233.154/32,0.0.0.0/0"
  authentication: "true"
  image:
    repository: trufflesuite/ganache-cli
    tag: latest
  service:
    type: ClusterIP